import Foundation
import AppKit

enum ClipboardPrivacy {
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        let types = pasteboard.types ?? []
        if types.contains(concealed) || types.contains(transient) || types.contains(autoGenerated) {
            return true
        }
        return false
    }
}
